services:
  server:
    build:
      context: .
      dockerfile: dev.fast.dockerfile
    image: sertfit-dev-img
    container_name: sertfit-dev
    env_file:
      - ./backend/.env.local
    environment:
      DB_HOST: pgdb
    networks:
      - sertfit-network
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www
    depends_on:
      pgdb:
        condition: service_healthy

  pgdb:
    image: postgres:17.5-alpine
    container_name: sertfit-db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: weloveroycee
    networks:
      - sertfit-network
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  pgdata:
    name: sertfit-data

networks:
  sertfit-network:
    name: sertfit-network
    driver: bridge